### ISSUE TITLE
Unable to get text (Data) dataref

### ISSUE THREAD

**Issue by crbascott** [nskillen/XP11_VA_Link#5]
Hey Nathan. I found some time to play with your plugins again. I was hoping to take advantage of retrieving text (data) datarefs but I'm getting an error.  I'm attaching the trace. Looks like data datarefs return a value that has to be decoded. Not sure if that is the issue or not.
![VA_Link_Data](https://user-images.githubusercontent.com/77812726/106549578-e1435f80-64d6-11eb-8de2-8ae6b6ffde27.JPG)

**Comment by nskillen** [comment]
Try this.
[XP11_VA_Link.zip](https://github.com/nskillen/XP11_VA_Link/files/5919979/XP11_VA_Link.zip)

**Comment by crbascott** [comment]
Working much better - thanks!
